include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = prefs

prefs_FILES = SIMRootListController.m
prefs_FRAMEWORKS = UIKit
prefs_PRIVATE_FRAMEWORKS = Preferences
prefs_EXTRA_FRAMEWORKS = Cephei CepheiPrefs
prefs_INSTALL_PATH = /Library/PreferenceBundles
prefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
